load("//tools/base/bazel:proto.bzl", "java_proto_library")

java_proto_library(
    name = "library_analyzer_java_proto",
    srcs = ["libraryanalyzerresult.proto"],
    visibility = [
        "//tools/vendor/google/keepgator:__subpackages__",
    ],
)
